### ISSUE TITLE
Suggestion: Display current elapsed time of song with total time on all themes

### ISSUE THREAD

**Issue by Milo123459** [kittinan/spotify-github-profile#17]
Just something that will display the time under the title of the song, ie

1:15/2:30

And maybe when it reaches 2:30 it can like update the svg to the next song or something? Not sure how that last one would work but yea

**Comment by ntsd** [comment]
from the API I think you can use timestamp, progress_ms, and duration_ms to calculate the current time 
what to do
1. pack these 3 fields into the template
2. write the javascript to the template to make the time sync with current timestamp

ref: https://developer.spotify.com/console/get-users-currently-playing-track

**Comment by kittinan** [comment]
not sure Github allow javascript in SVG but I found CSS can make a number counter

https://css-tricks.com/animating-number-counters/

**Comment by Milo123459** [comment]
Alright, I shall be hopefully contributing soon.
