### ISSUE TITLE
When nothing is being played, it will show random songs on your playlist

### ISSUE THREAD

**Issue by LucasMZReal** [kittinan/spotify-github-profile#20]
I have been having this issue on which it will show random songs from the playlist I left Spotify with, while I'm not listening to anything.

This is kind of annoying since you can't confirm if someone is actually listening to that song or not.

Not sure if this is an issue on my part but I don't think so? This doesn't seem to handle it properly when you're not listening to anything, adding support for that would be great! I would love to see support for it! :)

**Comment by ntsd** [comment]
It's feature writing here.

https://github.com/kittinan/spotify-github-profile/blob/716a50d2d70dc32f034d30c3e544141a4f1ddec0/api/view.py#L185
