### ISSUE TITLE
How can I change the position of the embed? (Not Issue)

### ISSUE THREAD

**Issue by mertbozkir** [kittinan/spotify-github-profile#21]
I want to align this Spotify music embed to the right position. 
![image](https://user-images.githubusercontent.com/63906053/126564950-48416905-6532-49d6-bf06-3176daedb6bf.png)

**I couldn't find it in markdown documentations.**

**Comment by kittinan** [comment]
Github markdown does not provide alignment ability. It is possible to use tag <img>, you should try it.

https://stackoverflow.com/questions/12090472/how-do-i-center-an-image-in-the-readme-md-on-github

**Comment by mertbozkir** [comment]
Thank you @kittinan, this issue is about div or CSS. I got it.
