### ISSUE TITLE
Bug when song name has "&" on it

### ISSUE THREAD

**Issue by ntsd** [kittinan/spotify-github-profile#3]
Fix in #2 

![image](https://user-images.githubusercontent.com/8283616/88119554-04698a00-cbeb-11ea-99af-648a1a1bb2db.png)

ref: https://stackoverflow.com/questions/3493405/do-i-really-need-to-encode-as-amp

**Comment by kittinan** [comment]
possible have bug on artist name too

**Comment by kittinan** [comment]
Fixed

![Screenshot from 2020-07-22 09:47:14](https://user-images.githubusercontent.com/144775/88128530-61236f80-cc00-11ea-9aa4-ac04ce592b55.png)
