### ISSUE TITLE
Function Crashed

### ISSUE THREAD

**Issue by Sam44323** [kittinan/spotify-github-profile#39]
The serverless functions have crashed. Can you check it once @kittinan ?
<img width="752" alt="Screenshot 2022-03-12 at 1 47 02 PM" src="https://user-images.githubusercontent.com/65643151/158010025-9af0a164-b5c1-4fe2-9e86-7f73ce4450cc.png">
?

**Comment by Daniel4-Scratch** [comment]
Having the same problem 👍

**Comment by utsanjan** [comment]
Same here :/

**Comment by MrDarkShadoow** [comment]
ok :(

**Comment by bhumikatewary** [comment]
Facing the same issue!

**Comment by Sabyasachi-Seal** [comment]
Same with me :). Had an idea though. What if we could replace this image with another image whenever we detected that this image is offline. For example. What if we set a default spotify image eg.See you Again song and then whenver the function is online, the real time image shows up and whenever its offline, the defualt image shows. It would act like a fault tolerance on the consumer's end.

**Comment by lamtonylam** [comment]
Having the same problem here too!

**Comment by Sabyasachi-Seal** [comment]
Hello everyone. I found a small fix for the timebeing. Just put the alt text to empty and the image logo will not appear. The now playing will directly showup when it is online.

**Comment by asthemus** [comment]
@kittinan is this project being supported?

**Comment by kittinan** [comment]
I will debug this issue tonight

**Comment by Lazylllama** [comment]
> Having the same problem 👍

YES WHATA FAKFAKAFKAFKFAKFAKFAKFAKFAKFAKFAAAKAKAFKAFK

**Comment by Daniel4-Scratch** [comment]
> > Having the same problem 👍
> 
> YES WHATA FAKFAKAFKAFKFAKFAKFAKFAKFAKFAKFAAAKAKAFKAFK

Bruh

**Comment by Lazylllama** [comment]
> > > Having the same problem 👍
> > 
> > 
> > YES WHATA FAKFAKAFKAFKFAKFAKFAKFAKFAKFAKFAAAKAKAFKAFK
> 
> Bruh

bbrruuhh

**Comment by kittinan** [comment]
To everyone, it is back to work now. it happened because `markupsafe` library updated and made our app crash.

I'm really sorry for the late response, I'm very busy on weekend.

https://github.com/aws/aws-sam-cli/issues/3661#issuecomment-1044340547

![Screenshot at 2022-03-14 18-04-53](https://user-images.githubusercontent.com/144775/158160157-a1f7577f-5a13-4695-a78b-8d6aafbcf203.png)
