### ISSUE TITLE
Can you possibly add auto refresh? or auto update.

### ISSUE THREAD

**Issue by unofficialdxnny** [kittinan/spotify-github-profile#56]
Hello basically as you know when the songs finish unless the page is refreshed the song doesn't update.

Can you add some sort of auto refresh on the element so it automatically updates on new song playing.

Thanks

**Comment by unofficialdxnny** [comment]
Hey so the reason I wanted to have this was because in my case I am using it for my [Website](https://unofficialdxnny.netlify.app/). I decided to get off my ass and actually make a function for it. If you are also using this feature for your site you are welcome.

```html
<img id="Spotify-now-playing" src="https://spotify-github-profile.vercel.app/api/view.svg?uid=ahmeddanial&cover_image=true&theme=novatorem&show_offline=true&background_color=121212&bar_color=f2aa4c&bar_color_cover=false" width="250" alt="Spotify-Down">
```
<img id="Spotify-now-playing" src="https://spotify-github-profile.vercel.app/api/view.svg?uid=ahmeddanial&cover_image=true&theme=novatorem&show_offline=true&background_color=121212&bar_color=f2aa4c&bar_color_cover=false" width="250" alt="Spotify-Down">

```js

setInterval(function() {
  var myImageElement = document.getElementById('Spotify-now-playing');
  myImageElement.src = 'https://spotify-github-profile.vercel.app/api/view.svg?uid=ahmeddanial&cover_image=true&theme=novatorem&show_offline=true&background_color=121212&bar_color=f2aa4c&bar_color_cover=false?rand=' + Math.random();
}, 5000);
```

**Comment by kittinan** [comment]
It does not work on Github. GitHub always cleans up javascript in an SVG images.

**Comment by unofficialdxnny** [comment]
> It does not work on Github. GitHub always cleans up javascript in an SVG images.

Yes thats true. I was trying to write an answer for people incase they want to use it in their website so i just left a `setInterval` function in my answer.

For GitHub you have no alternative at the moment other than refresh the browser.
