### ISSUE TITLE
API Not Work, 500 Error

### ISSUE THREAD

**Issue by dwisiswant0** [kittinan/spotify-github-profile#75]
https://spotify-github-profile.vercel.app/api/view

**Comment by dwisiswant0** [comment]
Seems like the site has been removed? https://spotify-github-profile.vercel.app/

**Comment by kittinan** [comment]
that works perfectly on my profile. Please try this link https://spotify-github-profile.vercel.app/api/login

![Screenshot at 2023-12-18 12-08-48](https://github.com/kittinan/spotify-github-profile/assets/144775/8bcbf5fd-0374-44ad-9762-666938c5825c)

**Comment by dwisiswant0** [comment]
Thanks for your prompt response, @kittinan. After I gave the app permission again, it started working. Seems like the 500 error happened because my account's password got updated when Spotify pushed for a password reset.

Once again, thank you @kittinan! Closing it now.

**Comment by dwisiswant0** [comment]
Wouldn't it be cooler if there was a specific design view for that thing? :D

**Comment by kittinan** [comment]
@dwisiswant0 thank you for your suggestion. :+1:
