### ISSUE TITLE
Host is down

### ISSUE THREAD

**Issue by dwisiswant0** [kittinan/spotify-github-profile#84]
![image](https://github.com/kittinan/spotify-github-profile/assets/25837540/38e9c416-be64-4579-b6ca-6f12fd882c58)

**Comment by Hoshino2123** [comment]
same to me

**Comment by kittinan** [comment]
Vercel paused my account due over limit free tier usage. I will deploy this project on self-host this weekend

![Screenshot at 2024-06-21 09-08-16](https://github.com/kittinan/spotify-github-profile/assets/144775/63b9f094-33ea-4dec-ad66-a991f3942830)

**Comment by Hoshino2123** [comment]
Ahhh ok, after that u learning we how to put Spotify on GitHub profile?

**Comment by kittinan** [comment]
Hi everyone, I setup new self-host at Digital Ocean San Francisco using Nginx and Docker.

Please replace old endpoint `https://spotify-github-profile.vercel.app` to `https://spotify-github-profile.kittinanx.com`.

Or create new badge at https://spotify-github-profile.kittinanx.com

**Comment by Hoshino2123** [comment]
Ty cutie

**Comment by arpy8** [comment]
let's gooo!

**Comment by dwisiswant0** [comment]
Thank you, @kittinan! I'll close this.
