### ISSUE TITLE
[Bug] Podcast Issue

### ISSUE THREAD

**Issue by bmusuko** [kittinan/spotify-github-profile#9]
## Description
Image won't show up when I listen to podcast on Spotify

**Comment by kittinan** [comment]
@bmusuko  Can you share some link of podcast?

**Comment by bmusuko** [comment]
[Philosophize Podcast](https://open.spotify.com/episode/5PM3tj3Zg8r0zMwtLTMQZf?si=k1r17fg3QWu1SPWo0OrYbw)
The error said `Error Fetching Resource`

**Comment by kittinan** [comment]
thanks for your information, I will fix it as soon as possible

**Comment by kittinan** [comment]
Fixed Podcast

![Screenshot at 2020-09-07 00-17-05](https://user-images.githubusercontent.com/144775/92331325-ec1cd400-f09f-11ea-94c3-9527ec490abf.png)

**Comment by bmusuko** [comment]
Thank you
