### ISSUE TITLE
It doesn't seem to work?

### ISSUE THREAD

**Issue by jackpurrin** [kittinan/spotify-github-profile#99]
Whenever I click on the 'Connect to spotify' button and then configure to my liking, it doesn't work. Then pressing copy and putting it in my README.md file it doesn't do anything, but make a link.

Is it user error, or is it broken?

**Comment by jackpurrin** [comment]
On further analysis, it seems to be an issue with the generator website. It does work, you just have to make it an image yourself. Not sure if to close, so I'll let the repo owner do it.

**Comment by kittinan** [comment]
please give me a screenshot

**Comment by jackpurrin** [comment]
just user error.
